services:
- type: web
  name: polarimetry-dashboard
  runtime: python
  repo: https://github.com/aqstrw/polarimetry-dashboard
  plan: free
  envVars:
  - key: PYTHON_VERSION
    value: 3.12
    sync: false
  region: oregon
  buildCommand: python3 -m pip install --upgrade packaging && pip install -r requirements.txt
  startCommand: gunicorn --chdir src app:server
version: "1"

